### ISSUE TITLE
Fix example link and improve

### ISSUE THREAD

**Issue by alexchandel** [withkittens/rust-com#4]
The example source should be kept in the tree.

Moreover, it should depict how an arbitrary COM interface can be used from Rust. For example, [OPC](https://github.com/mascarenhas/luacomgen/tree/master/opc).

**Comment by JoeyAcc** [comment]
This bug is a year and a half old, yet hasn't been fixed since then. 
Is this project maintained at all?

**Comment by withkittens** [comment]
@JoeyAcc, no, I don't maintain this project anymore, I'm sorry.

I'll try to contact Rust developers to know whether it's possible to free the package name for other people, or at least transfer the ownership.

**Comment by JoeyAcc** [comment]
Before you remove the crate, does it actually work?
That is, can it actually load and manipulate COM objects?

Because if it can, it can still be of use to me as that is precisely what I need to achieve ATM.

**Comment by withkittens** [comment]
@JoeyAcc, please look at these gists, I hope they can help you. IIRC, I was able to use COM objects successfully.

https://gist.github.com/withkittens/73a596618df3ad5811f3
https://gist.github.com/withkittens/f1363cc25a807374c24d
https://gist.github.com/withkittens/57ac8759c0689142b287
https://gist.github.com/withkittens/95c3a94216d8138551f5

**Comment by JoeyAcc** [comment]
Thanks for these! I'll have a look.

**Comment by withkittens** [comment]
Also please note, it was Rust 1.0 then, and now we have Rust 1.19 or 1.20, I don't know for sure. Just **LOTS** of things changed since then.

**Comment by withkittens** [comment]
@JoeyAcc, I'd like to ask you to save these gist links somewhere if you still need them, as I want to delete this repository in couple of days.

**Comment by JoeyAcc** [comment]
I have forked both the repo and the Gists. 
Assuming that GitHub treats forks as full copies, your version should be safe to delete.
